### ISSUE TITLE
How is the reference path tracked by MPC generated? 

### ISSUE THREAD

**Issue by MandyZhang4869** [CMU-TBD/Group_baed_navigation_v1#1]
I have been troubled by a question for a long time. Based on my understanding, it seems that using MPC requires specifying a reference trajectory, doesn't it?
If so, how is the reference trajectory for MPC tracking generated in your approach?

looking forward to your reply!!!!!! thank you

**Comment by allanwangliqian** [comment]
Thank you for your question! In our case, the reference trajectory could be the one generated with the knowledge of what all groups will look like in ground truth in the future. But because we don't know the ground truths of future groups, we don't really have access to this reference trajectory to converge to. So we are using a much simpler formulation and simply treat the goal as the reference variable.

**Comment by MandyZhang4869** [comment]
Are you saying that you did not generate a reference trajectory, but
instead set a waypoint (designated as the robot's destination), and used
the cost Jg to guide the robot towards the waypoint?

And, in practice, MPC can run without a reference trajectory? So, what is
the feedback correction of the MPC based on if there is no reference
trajectory?

looking forward to your reply！！！！！thank you

**Comment by allanwangliqian** [comment]
The feedback is on whether the robot has reached the waypoint or not. Our MPC is very simple. If you want to think of it in terms of trajectories, the reference trajectory is a straight line to the waypoint.

**Comment by MandyZhang4869** [comment]
I see， thank you！！！！
